include:
  - path: ./docker-compose-base.yml
    env_file: ./.env

services:
  ragflow:
    depends_on:
      mysql:
        condition: service_healthy
      es01:
        condition: service_healthy
      llama:
        condition: service_healthy
    image: ${RAGFLOW_IMAGE}
    container_name: ragflow-server
    ports:
      - ${SVR_HTTP_PORT}:9380
      - 8991:80
      - 7443:443
      - 5678:5678
    volumes:
      - ./service_conf.yaml:/ragflow/conf/service_conf.yaml
      - ./ragflow-logs:/ragflow/logs
      - ./nginx/ragflow.conf:/etc/nginx/conf.d/ragflow.conf
      - ./nginx/proxy.conf:/etc/nginx/proxy.conf
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    environment:
      - TZ=${TIMEZONE}
      - HF_ENDPOINT=${HF_ENDPOINT}
      - MACOS=${MACOS}
    networks:
      - ragflow
    restart: always
    extra_hosts:
      - "host.docker.internal:host-gateway"

  ## docker pull ghcr.io/ggerganov/llama.cpp:server
  llama:
    image: ghcr.io/ggerganov/llama.cpp:server
    container_name: ragflow-llama
    ports:
      - ${LLAMA_PORT:-8000}:8000
    volumes:
      - ./models:/models
    environment:
      - TZ=${TIMEZONE}
    command: >
      -m /models/qwen2.5-1.5b-instruct-q4_0.gguf
      --port 8000
      --host 0.0.0.0
      -n 512
      -t 8
      -c 4096
      --cont-batching
      --cache-reuse 512
      --no-mmap
      -ngl 20
      --prio 3
      -np 4
    networks:
      - ragflow
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8000/health" ]
      interval: 10s
      timeout: 10s
      retries: 3
    restart: always
    extra_hosts:
      - "host.docker.internal:host-gateway"